# Generated by Django 4.0.3 on 2022-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='class_tests',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='due',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='class_tests',
            name='occurring',
            field=models.DateTimeField(),
        ),
    ]
