# Generated by Django 4.0.3 on 2022-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_announcements_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_tests',
            name='type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('written', 'Written')], default='mcq', max_length=10),
        ),
    ]
