# Generated by Django 4.0.3 on 2022-03-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_class_tests_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='class_tests',
            name='type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('written', 'Written')], default='mcq', max_length=10),
        ),
    ]
