# Generated by Django 4.0.3 on 2022-03-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_demo_alter_class_tests_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.AlterField(
            model_name='class_tests',
            name='type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('written', 'Written')], default='mcq', max_length=10),
        ),
    ]
