# Generated by Django 4.0.3 on 2022-03-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_delete_demo_alter_class_tests_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpwewant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=7)),
                ('question', models.TextField(blank=True, max_length=500)),
                ('answered_by', models.TextField(max_length=15)),
                ('asnwer', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='class_tests',
            name='type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('written', 'Written')], default='mcq', max_length=10),
        ),
    ]
