# Generated by Django 4.0.3 on 2022-03-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_helpwewant_alter_class_tests_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_tests',
            name='type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('written', 'Written')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpwewant',
            name='answered_by',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='helpwewant',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
