# Generated by Django 4.0.3 on 2022-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_alter_assignments_created_at_alter_class_tests_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_tests',
            name='type',
            field=models.CharField(choices=[('mcq', 'Mcq'), ('written', 'Written')], default='mcq', max_length=10),
        ),
    ]
